[book]
title = "コードリーディング: vLLM"
authors = [""]
language = "ja"

[output.html]
git-repository-url = ""
edit-url-template = ""
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["theme/custom.css"]

[output.html.search]
enable = true

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.playground]
editable = false
